os: osx
osx_image: xcode11
language: objective-c
cache:
  directories:
    - Carthage/
install:
  - gem install cocoapods
  - pod repo update
  - carthage update --platform $PLATFORM
before_script: 
  - pod lib lint
  - swiftlint
matrix:
  include:
    - env: PLATFORM=macOS DESTINATION='platform=macOS,arch=x86_64'
    - env: PLATFORM=iOS DESTINATION='platform=iOS Simulator,name=iPhone 11'
    - env: PLATFORM=tvOS DESTINATION='platform=tvOS Simulator,name=Apple TV'
    - env: PLATFORM=watchOS
script:
  - ./scripts/run_tests
