#!/usr/bin/env bash

PROJECT=RxSpriteKit.xcodeproj

if [[ $PLATFORM = "iOS" ]]; then
  DESTINATION='platform=iOS Simulator,name=iPhone 11'
elif [[ $PLATFORM = "macOS" ]]; then
  DESTINATION='platform=macOS,arch=x86_64'
else
  DESTINATION='platform=tvOS Simulator,name=Apple TV 4K'
fi

xcodebuild test -project $PROJECT -scheme RxSpriteKit-$PLATFORM -destination "${DESTINATION}"
xcodebuild -project $PROJECT -scheme RxSpriteKitDemo-$PLATFORM -destination "${DESTINATION}"
