#!/usr/bin/env bash

PROJECT=RxSpriteKit.xcodeproj

if [[ $PLATFORM == watchOS ]]; then
  xcodebuild -project $PROJECT -scheme RxSpriteKit-$PLATFORM -destination 'platform=watchOS Simulator,name=Apple Watch Series 3 - 42mm'
else
  xcodebuild test -project $PROJECT -scheme RxSpriteKit-$PLATFORM -destination "${DESTINATION}"
fi
