name: RxSpriteKit

on: [push]

jobs:
  build:
    runs-on: macos
    strategy:
      matrix:
        platform: [iOS, macOS, tvOS]
    env: 
      PLATFORM: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - name: Install Dependencies
      run: |
        carthage update --platform $PLATFORM
    - name: Run Tests and Build Demos
      run: ./scripts/run_tests
