name: RxSpriteKit

on: [push]

jobs:
  build:
    runs-on: macos
    strategy:
      matrix:
        platform: [iOS, macOS, watchOS, tvOS]
    env: 
      PLATFORM: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - name: Install Dependencies
      run: |
        gem install cocoapods
        pod repo update
        carthage update --platform $PLATFORM
        brew install swiftlint
    - name: SwiftLint
      run: swiftlint --strict
    - name: CocoaPods
      run: pod lib lint
    - name: Run Tests and Build Demos
      run: ./scripts/run_tests
