name: Lint

on: [push]

jobs:
  build:
    runs-on: macos
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        gem install cocoapods
        pod repo update
        brew install swiftlint
    - name: SwiftLint
      run: swiftlint --strict
    - name: CocoaPods
      run: pod lib lint
